apiVersion: rkeprep/v2
kind: Agent
metadata:
  name: dc1domain-work02
spec:
  hostname: dc1domain-work02
  nodeIp: 10.1.4.149
  bindAddress: 10.1.4.149
  advertiseAddress: 10.1.4.149
  cni:
    - multus
    - canal
  interfaces:
    - name: eth0
      ip: 10.1.4.149
      prefix: 24
      gateway: 10.1.4.1
      dns: ["10.1.4.2"]
    - name: eth1
      ip: 172.16.10.117
      prefix: 24
    - name: eth2
      ip: 192.168.1.149
      prefix: 24
    - name: eth3
      ip: 1.1.0.149
      prefix: 25
  serverURL: https://10.1.4.141:9345
  tokenFile: /rke2-node-init/outputs/dc1domain-ca-bootstrap-token.txt
  node-label:
    - "role=worker"
    - "env=preprod"
  customCA:
    rootCrt: /rke2-node-init/configs/preprod/certs/root-ca.crt
    rootKey: /rke2-node-init/configs/preprod/certs/root-ca-key.pem
    installToOSTrust: true
  disable:
    - rke2-ingress-nginx
    - rke2-ingress-traefik
