apiVersion: rkeprep/v2
kind: Server
metadata:
  name: dc2domain-ctrl01
spec:
  hostname: dc2domain-ctrl01
  nodeIp: 10.2.4.161
  bindAddress: 10.2.4.161
  advertiseAddress: 10.2.4.161
  cni:
    - multus
    - canal
  interfaces:
    - name: eth0
      ip: 10.2.4.161
      prefix: 24
      gateway: 10.2.4.1
      dns: ["10.2.4.2"]
    - name: eth1
      ip: 172.16.20.116
      prefix: 24
    - name: eth2
      ip: 192.168.2.161
      prefix: 24
    - name: eth3
      ip: 1.2.0.161
      prefix: 25
  node-label:
    - "node-role.kubernetes.io/control-plane=true"
    - "node-role.kubernetes.io/worker=true"
  node-taint:
    - "node-role.kubernetes.io/control-plane:NoSchedule"
  tls-san:
    - dc2domain-ctrl01
    - dc2domain-ctrl01.dev.kube
    - dc2domain-cluster
    - dc2domain-cluster.dev.kube
    - 10.2.4.161
  cluster-domain: cluster.local
  enable-servicelb: "false"
  embedded-registry: true
  disable-default-registry-endpoint: true
  kube-apiserver-arg:
    - "audit-log-maxage=15"
  disable:
    - rke2-ingress-nginx
    - rke2-ingress-traefik
  customCA:
    rootCrt: /rke2-node-init/configs/preprod/certs/root-ca.crt
    rootKey: /rke2-node-init/configs/preprod/certs/root-ca-key.pem
    installToOSTrust: true
  service-cidr: 10.96.0.0/16
  cluster-cidr: 10.246.0.0/16
  tokenFile: /rke2-node-init/outputs/dc2domain-ca-bootstrap-token.txt
