#cloud-config
hostname: dc3domain-ctrl01
write_files:
  - path: /etc/hosts
    content: |
      127.0.0.1 localhost
      10.3.4.181 dc3domain-ctrl01

network:
  version: 2
  ethernets:
    eth0:
      dhcp4: false
      addresses: [10.3.4.181/24]
      gateway4: 10.3.4.1
      nameservers:
        addresses: [10.3.4.2]
    eth1:
      dhcp4: false
      addresses: [172.16.30.123/24]
    eth2:
      dhcp4: false
      addresses: [192.168.3.181/24]
    eth3:
      dhcp4: false
      addresses: [1.3.0.181/25]

runcmd:
  - curl -sfL https://get.rke2.io | INSTALL_RKE2_TYPE="server" sh -
  - systemctl enable rke2-server.service
  - systemctl start rke2-server.service
  - mkdir -p /etc/rancher/rke2
  - cat > /etc/rancher/rke2/config.yaml <<'EOF'
node-label:
  - "node-role.kubernetes.io/control-plane=true"
  - "node-role.kubernetes.io/worker=true"
service-cidr: 10.98.0.0/16
cluster-cidr: 10.248.0.0/16
EOF

final_message: "dc3domain-ctrl01 cloud-init applied"
