flowchart TB
  BYOD[External BYOD User]
  AVD[AVD Clients<br>Appgate Client/Agent]
  GW1[SDPG Gateway]
  GW2[SDPT Connector]
  CTRL[SDPC Controller]
  PR[Protected Resources<br>Inside + Dev + SEG]

  BYOD -->|AVD access Microsoft AVD broker/control plane| AVD
  AVD -->|tcp/udp 443 + udp 53| CTRL
  AVD -->|tcp/udp 443 + udp 53| GW1
  CTRL -->|tcp/udp 443 + udp 53| GW1
  CTRL -->|tcp/udp 443 + udp 53| GW2
  AVD -->|tcp/udp 443 + udp 53| GW2
  GW1 -->|All Ports| PR
  GW2 ---|All Ports| PR

  class CTRL,GW1,GW2 sdpc
  classDef sdpc fill:#FFA500,stroke:#FF0000,stroke-width:2px,color:#000000

  class BYOD enduser
  classDef enduser fill:#ffe9d6,stroke:#e07a2c,stroke-width:2px,color:#000000

  class AVD client
  classDef client fill:#e6f7ff,stroke:#28a745,stroke-width:2px,color:#000000

  class PR,DOMAIN,DEV,SEG sdpgsvc
  classDef sdpgsvc fill:#f0e6ff,stroke:#28a745,stroke-width:2px,color:#000000

  class DOMSVC,DEVSVC,HWIL sdptsvc
  classDef sdptsvc fill:#f1f700,stroke:#28a745,stroke-width:2px,color:#000000
 
