flowchart TB
  BYOD[External BYOD User]
  subgraph CONTROL_PLANE[SDP Control Plane]
    direction LR
  AVD[Azure Virtual<br>Desktop<br>Appgate Client<br>201.1.2.0/24<br>202.1.2.0/24]
  CTRL[SDP Controller<br>201.0.1.0/24<br>202.0.1.0/24]
  end

  subgraph DATA_PLANE[SDP Data Plane]
    direction LR
    subgraph GW2_LANE[Protected Services]
      direction TB
      GW2[SDP Connector<br>201.0.3.0/24<br>202.0.3.0/24]
      DOMSVC[DOMAIN SERVICES<br>201.1.1.0/24<br>202.1.1.0/24]
      DEVSVC[DEV SERVICES<br>201.2.1.0/24<br>202.2.1.0/24]
      HWIL[HWIL<br>201.3.1.0/24<br>202.3.1.0/24]
    end

    subgraph GW1_LANE[Protected Resources]
      direction TB
      GW1[SDP Gateway<br>201.0.2.0/24<br>202.0.2.0/24]
      DOMAIN[DOMAIN<br>201.1.0.0/24<br>202.1.0.0/24]
      DEV[DEV<br>201.2.0.0/24<br>202.2.0.0/24]
      SEG[SEG<br>201.3.0.0/24<br>202.3.0.0/24]
    end
  end


  BYOD -->|Internet| AVD
  AVD -->|tcp/udp 443 + udp 53| CTRL
  AVD -->|tcp/udp 443 + udp 53| GW2
  CTRL -->|tcp/udp 443 + udp 53| GW1
  AVD -->|tcp/udp 443 + udp 53| GW1
  CTRL -->|tcp/udp 443 + udp 53| GW2

  GW1 -->|All Ports| DOMAIN
  GW1 -->|All Ports| DEV
  GW1 -->|All Ports| SEG

  GW2 -->|All Ports| DOMSVC
  GW2 -->|All Ports| DEVSVC
  GW2 -->|All Ports| HWIL

  class CTRL,GW1,GW2 sdpc
  classDef sdpc fill:#FFA500,stroke:#FF0000,stroke-width:2px,color:#000000

  class BYOD enduser
  classDef enduser fill:#ffe9d6,stroke:#e07a2c,stroke-width:2px,color:#000000

  class AVD client
  classDef client fill:#e6f7ff,stroke:#28a745,stroke-width:2px,color:#000000

  class DOMAIN,DEV,SEG sdpgsvc
  classDef sdpgsvc fill:#f0e6ff,stroke:#28a745,stroke-width:2px,color:#000000

  class DOMSVC,DEVSVC,HWIL sdptsvc
  classDef sdptsvc fill:#f0e6ff,stroke:#28a745,stroke-width:2px,color:#000000
 
