flowchart LR
  %% Default routes (northbound)
  AZ_INSIDE[AZ inside.vyos\n0.0.0.0/0 -> 201.0.0.1] --> AZ_CORE[AZ core.vyos\n0.0.0.0/0 -> 201.0.0.2]
  AZ_DEV[AZ developer.vyos\n0.0.0.0/0 -> 201.0.0.1] --> AZ_CORE
  AZ_SEG1[AZ segment1.vyos\n0.0.0.0/0 -> 201.0.0.1] --> AZ_CORE
  AZ_CORE --> AZ_EDGE[AZ edge.vyos\n0.0.0.0/0 -> 201.254.0.2]
  AZ_EDGE --> AZ_EXT[AZ external.vyos\n0.0.0.0/0 -> 201.255.0.1 (blocked)]

  ONP_INSIDE[ONP inside.vyos\n0.0.0.0/0 -> 202.0.0.1] --> ONP_CORE[ONP core.vyos\n0.0.0.0/0 -> 202.0.0.2]
  ONP_DEV[ONP developer.vyos\n0.0.0.0/0 -> 202.0.0.1] --> ONP_CORE
  ONP_SEG1[ONP segment1.vyos\n0.0.0.0/0 -> 202.0.0.1] --> ONP_CORE
  ONP_CORE --> ONP_EDGE[ONP edge.vyos\n0.0.0.0/0 -> 202.254.0.2]
