%% eth0 = VYOS-OOB via Hyper-V Default Switch (DHCP) for all routers
flowchart LR
  MGMT(("VYOS-OOB / Default Switch<br>DHCP / eth0"))

  %% Azure
  subgraph AZ["Azure (201.x)"]
    AZ_EXT["external.vyos<br>AZ-WAN eth1 201.255.0.2/24<br>AZ-EXT eth2 201.254.0.2/24<br>AZ-WAN CLOSED"]
    AZ_EDGE["edge.vyos<br>AZ-EXT eth1 201.254.0.1/24<br>AZ-DREN eth2 100.255.0.1/24<br>AZ-CORE eth3 201.0.0.2/24"]
    AZ_CORE["core.vyos<br>AZ-CORE eth1 201.0.0.1/24<br>SDPC 201.0.1.1/24<br>SDPG 201.0.2.1/24<br>SDPT 201.0.3.1/24"]
    AZ_INSIDE["inside.vyos<br>AZ-CORE 201.0.0.3/24<br>DOMAIN 201.1.0.1/24<br>DOMSVC 201.1.1.1/24<br>AVD 201.1.2.1/24"]
    AZ_DEV["developer.vyos<br>AZ-CORE 201.0.0.4/24<br>DEV 201.2.0.1/24<br>DEVSVC 201.2.1.1/24"]
    AZ_SEG1["segment1.vyos<br>AZ-CORE 201.0.0.5/24<br>SEG 201.3.0.1/24<br>HWIL 201.3.1.1/24"]
  end

  %% On-prem
  subgraph ONP["On-Prem (202.x)"]
    ONP_EDGE["edge.vyos<br>ONP-EXT eth1 202.254.0.1/24<br>ONP-DREN eth2 100.255.0.2/24<br>ONP-CORE eth3 202.0.0.2/24"]
    ONP_CORE["core.vyos<br>ONP-CORE eth1 202.0.0.1/24<br>SDPC 202.0.1.1/24<br>SDPG 202.0.2.1/24<br>SDPT 202.0.3.1/24"]
    ONP_INSIDE["inside.vyos<br>ONP-CORE 202.0.0.3/24<br>DOMAIN 202.1.0.1/24<br>DOMSVC 202.1.1.1/24<br>AVD 202.1.2.1/24"]
    ONP_DEV["developer.vyos<br>ONP-CORE 202.0.0.4/24<br>DEV 202.2.0.1/24<br>DEVSVC 202.2.1.1/24"]
    ONP_SEG1["segment1.vyos<br>ONP-CORE 202.0.0.5/24<br>SEG 202.3.0.1/24<br>HWIL 202.3.1.1/24"]
  end

  %% Networks
  AZWAN(("AZ-WAN<br>201.255.0.0/24"))
  AZEXT(("AZ-EXT<br>201.254.0.0/24"))
  AZCORENET(("AZ-CORE<br>201.0.0.0/24"))
  ONPEXT(("ONP-EXT<br>202.254.0.0/24"))
  ONPCORENET(("ONP-CORE<br>202.0.0.0/24"))
  DREN(("DREN<br>100.255.0.0/24<br>ALLOW: ICMP, 443/TCP+UDP, 53/UDP"))

  %% mgmt
  MGMT --- AZ_EXT
  MGMT --- AZ_EDGE
  MGMT --- AZ_CORE
  MGMT --- AZ_INSIDE
  MGMT --- AZ_DEV
  MGMT --- AZ_SEG1
  MGMT --- ONP_EDGE
  MGMT --- ONP_CORE
  MGMT --- ONP_INSIDE
  MGMT --- ONP_DEV
  MGMT --- ONP_SEG1

  %% Azure links
  AZWAN --- AZ_EXT
  AZEXT --- AZ_EXT
  AZEXT --- AZ_EDGE
  AZCORENET --- AZ_EDGE
  AZCORENET --- AZ_CORE
  AZCORENET --- AZ_INSIDE
  AZCORENET --- AZ_DEV
  AZCORENET --- AZ_SEG1

  %% On-prem links
  ONPEXT --- ONP_EDGE
  ONPCORENET --- ONP_EDGE
  ONPCORENET --- ONP_CORE
  ONPCORENET --- ONP_INSIDE
  ONPCORENET --- ONP_DEV
  ONPCORENET --- ONP_SEG1

  %% DREN
  AZ_EDGE --- DREN --- ONP_EDGE
